"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
type Profile={name:string;profile:string};
const DEFAULTS:Profile[]=[{name:"Personal",profile:"Default"},{name:"Work",profile:"Profile 1"},{name:"Side projects",profile:"Profile 2"}];
function score(query:string,candidate:string){const q=query.trim().toLowerCase(),c=candidate.toLowerCase();if(!q)return-1;if(c===q)return 100;if(c.startsWith(q))return 80-c.length+q.length;if(c.includes(q))return 60-c.indexOf(q);let points=0,cursor=0;for(const letter of q){const next=c.indexOf(letter,cursor);if(next<0)return-1;points+=3-Math.min(next-cursor,2);cursor=next+1}return points}
export default function Home(){
 const dialogRef=useRef<HTMLDialogElement>(null),inputRef=useRef<HTMLInputElement>(null);const[query,setQuery]=useState(""),[submitted,setSubmitted]=useState(false),[status,setStatus]=useState("Ready when you are"),[profiles,setProfiles]=useState(DEFAULTS);
 useEffect(()=>{navigator.serviceWorker?.register("/sw.js");fetch("http://127.0.0.1:47321/profiles").then(r=>r.ok?r.json():Promise.reject()).then(items=>{if(Array.isArray(items)&&items.length)setProfiles(items)}).catch(()=>setStatus("Launcher helper is offline · Preview mode"))},[]);
 function openDialog(){setQuery("");setSubmitted(false);dialogRef.current?.showModal();requestAnimationFrame(()=>inputRef.current?.focus())}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openDialog()}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
 const matches=useMemo(()=>profiles.map(item=>({...item,rank:score(query,item.name)})).filter(item=>item.rank>=0).sort((a,b)=>b.rank-a.rank),[profiles,query]);
 async function launch(item:Profile){setStatus(`Opening ${item.name}…`);dialogRef.current?.close();try{const response=await fetch("http://127.0.0.1:47321/open",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile:item.profile})});if(!response.ok)throw Error();setStatus(`${item.name} opened in Microsoft 365 Admin`)}catch{setStatus(`Matched ${item.name} · Connect the helper to launch`)}}
 function find(event:FormEvent){event.preventDefault();setSubmitted(true);if(matches.length===1)launch(matches[0])}
 return <main><header className="topbar"><a className="brand" href="#top"><img className="brandMark" src="/pk-logo.svg" alt="PK"/>Chrome Helper</a><div className="connection"><span className="pulse"/>{status}</div></header>
 <section className="hero" id="top"><div className="eyebrow">Chrome profile launcher</div><h1>Choose a profile.<br/><em>Get straight to admin.</em></h1><button className="launchButton" onClick={openDialog} aria-label="Choose a Chrome profile"><span className="plus">+</span><span>Open profile</span><kbd>⌘ K</kbd></button><p className="lede">Type a name. Pick a match. Land directly in Microsoft 365 Admin.</p></section>
 <div className="destination"><span>Always opens</span><strong>admin.microsoft.com</strong><span className="north">↗</span></div>
 <dialog ref={dialogRef} onClick={e=>{if(e.target===dialogRef.current)dialogRef.current.close()}}><form onSubmit={find}><button type="button" className="close" onClick={()=>dialogRef.current?.close()} aria-label="Close">×</button><label htmlFor="profile-name">Which profile?</label><p>Type a name — close matches work too.</p><div className="inputRow"><span className="searchIcon">⌕</span><input ref={inputRef} id="profile-name" value={query} onChange={e=>{setQuery(e.target.value);setSubmitted(false)}} placeholder="e.g. naaja" autoComplete="off"/><button type="submit" disabled={!query.trim()}>Find <span>↗</span></button></div>{submitted&&<div className="results" aria-live="polite">{matches.length>1&&<h2>{matches.length} matching profiles</h2>}{matches.length===0&&<div className="empty">No matching profiles found.</div>}{matches.map((item,index)=><button type="button" className="resultButton" key={item.profile} onClick={()=>launch(item)}><span className={`avatar tone${index%3+1}`}>{item.name[0]}</span><span><strong>{item.name}</strong><small>{item.profile}</small></span><span className="arrow">Open ↗</span></button>)}</div>}</form></dialog>
 <footer>Built for Chrome on desktop <span>·</span> Your profiles stay on this device</footer></main>}
