"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
type Profile={name:string;profile:string}; type Recent=Profile&{at:number};
const DEFAULTS:Profile[]=[{name:"Personal",profile:"Default"},{name:"Work",profile:"Profile 1"},{name:"Side projects",profile:"Profile 2"}];
function score(query:string,candidate:string){const q=query.trim().toLowerCase(),c=candidate.toLowerCase();if(!q)return 0;if(c===q)return 100;if(c.startsWith(q))return 80-c.length+q.length;if(c.includes(q))return 60-c.indexOf(q);let points=0,cursor=0;for(const letter of q){const next=c.indexOf(letter,cursor);if(next<0)return-1;points+=3-Math.min(next-cursor,2);cursor=next+1}return points}
export default function Home(){
 const dialogRef=useRef<HTMLDialogElement>(null),inputRef=useRef<HTMLInputElement>(null);const[query,setQuery]=useState(""),[status,setStatus]=useState("Ready when you are"),[recent,setRecent]=useState<Recent[]>([]),[profiles,setProfiles]=useState(DEFAULTS);
 useEffect(()=>{navigator.serviceWorker?.register("/sw.js");const saved=localStorage.getItem("switchboard-recents");if(saved)try{setRecent(JSON.parse(saved))}catch{}fetch("http://127.0.0.1:47321/profiles").then(r=>r.ok?r.json():Promise.reject()).then(items=>{if(Array.isArray(items)&&items.length)setProfiles(items)}).catch(()=>setStatus("Launcher helper is offline · Preview mode"))},[]);
 function openDialog(value=""){setQuery(value);dialogRef.current?.showModal();requestAnimationFrame(()=>inputRef.current?.focus())}
 async function launch(event:FormEvent){event.preventDefault();const best=[...profiles].sort((a,b)=>score(query,b.name)-score(query,a.name))[0];if(!best||score(query,best.name)<0){setStatus(`No profile found for “${query}”`);dialogRef.current?.close();return}setStatus(`Opening ${best.name}…`);dialogRef.current?.close();try{const response=await fetch("http://127.0.0.1:47321/open",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile:best.profile})});if(!response.ok)throw Error();setStatus(`${best.name} is open`)}catch{setStatus(`Matched ${best.name} · Connect the helper to launch`)}const next=[{...best,at:Date.now()},...recent.filter(item=>item.profile!==best.profile)].slice(0,3);setRecent(next);localStorage.setItem("switchboard-recents",JSON.stringify(next))}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openDialog()}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
 const best=query?[...profiles].sort((a,b)=>score(query,b.name)-score(query,a.name))[0]:null;
 return <main><header className="topbar"><a className="brand" href="#top"><span className="brandMark">S</span>Switchboard</a><div className="connection"><span className="pulse"/>{status}</div></header>
 <section className="hero" id="top"><div className="eyebrow">Chrome profile launcher</div><h1>Your next window,<br/><em>one name away.</em></h1><p className="lede">Tap the button, say who you need, and Switchboard finds the closest Chrome profile.</p><button className="launchButton" onClick={()=>openDialog()} aria-label="Open a Chrome profile"><span className="plus">+</span><span>Open profile</span><kbd>⌘ K</kbd></button></section>
 <section className="recents"><div className="sectionHeading"><h2>Recent profiles</h2><span>{recent.length||profiles.length} available</span></div><div className="profileGrid">{(recent.length?recent:profiles).slice(0,3).map((item,index)=><button key={item.profile} className="profileCard" onClick={()=>openDialog(item.name)}><span className={`avatar tone${index+1}`}>{item.name[0]}</span><span><strong>{item.name}</strong><small>{item.profile}</small></span><span className="arrow">↗</span></button>)}</div></section>
 <dialog ref={dialogRef} onClick={e=>{if(e.target===dialogRef.current)dialogRef.current.close()}}><form onSubmit={launch}><button type="button" className="close" onClick={()=>dialogRef.current?.close()} aria-label="Close">×</button><label htmlFor="profile-name">Which profile?</label><p>Type a name — close matches work too.</p><div className="inputRow"><span className="searchIcon">⌕</span><input ref={inputRef} id="profile-name" value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Personal or Work" autoComplete="off"/><button type="submit" disabled={!query.trim()}>Open <span>↗</span></button></div>{best&&<div className="match">Best match: <strong>{best.name}</strong></div>}</form></dialog><footer>Built for Chrome on desktop <span>·</span> Your profiles stay on this device</footer></main>}
