"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
type Profile={name:string;profile:string};
type PipApi={requestWindow:(options:{width:number;height:number})=>Promise<Window>};
const DEFAULTS:Profile[]=[{name:"Personal",profile:"Default"},{name:"Work",profile:"Profile 1"},{name:"Side projects",profile:"Profile 2"}];
function score(query:string,candidate:string){const q=query.trim().toLowerCase(),c=candidate.toLowerCase();if(!q)return-1;if(c===q)return 100;if(c.startsWith(q))return 80-c.length+q.length;if(c.includes(q))return 60-c.indexOf(q);let points=0,cursor=0;for(const letter of q){const next=c.indexOf(letter,cursor);if(next<0)return-1;points+=3-Math.min(next-cursor,2);cursor=next+1}return points}
export default function Home(){
 const dialogRef=useRef<HTMLDialogElement>(null),inputRef=useRef<HTMLInputElement>(null),pipRef=useRef<Window|null>(null);const[query,setQuery]=useState(""),[submitted,setSubmitted]=useState(false),[status,setStatus]=useState("Ready when you are"),[profiles,setProfiles]=useState(DEFAULTS);
 useEffect(()=>{navigator.serviceWorker?.register("/sw.js");fetch("http://127.0.0.1:47321/profiles").then(r=>r.ok?r.json():Promise.reject()).then(items=>{if(Array.isArray(items)&&items.length)setProfiles(items)}).catch(()=>setStatus("Launcher helper is offline · Preview mode"))},[]);
 function openDialog(){setQuery("");setSubmitted(false);dialogRef.current?.showModal();requestAnimationFrame(()=>inputRef.current?.focus())}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openDialog()}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
 const matches=useMemo(()=>profiles.map(item=>({...item,rank:score(query,item.name)})).filter(item=>item.rank>=0).sort((a,b)=>b.rank-a.rank),[profiles,query]);
 async function launch(item:Profile,closeMain=true){setStatus(`Opening ${item.name}…`);if(closeMain)dialogRef.current?.close();try{const response=await fetch("http://127.0.0.1:47321/open",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile:item.profile})});if(!response.ok)throw Error();setStatus(`${item.name} opened in Microsoft 365 Admin`)}catch{setStatus(`Matched ${item.name} · Connect the helper to launch`)}}
 function find(event:FormEvent){event.preventDefault();setSubmitted(true);if(matches.length===1)launch(matches[0])}

 function renderPipHome(pip:Window){const root=pip.document.getElementById("root")!;root.innerHTML='<button class="pip-plus" aria-label="Find a Chrome profile">+</button>';root.querySelector("button")!.addEventListener("click",()=>renderPipSearch(pip))}
 function renderPipSearch(pip:Window){const root=pip.document.getElementById("root")!;root.innerHTML='<form class="pip-search"><label for="pip-name">Which profile?</label><input id="pip-name" placeholder="e.g. naaja" autocomplete="off"><button type="submit">Find</button><div class="pip-results"></div><button class="pip-back" type="button">← Back</button></form>';const form=root.querySelector("form")!,input=root.querySelector("input")!,results=root.querySelector(".pip-results")!;root.querySelector(".pip-back")!.addEventListener("click",()=>renderPipHome(pip));form.addEventListener("submit",async event=>{event.preventDefault();const found=profiles.map(item=>({...item,rank:score(input.value,item.name)})).filter(item=>item.rank>=0).sort((a,b)=>b.rank-a.rank);if(found.length===1){await launch(found[0],false);renderPipHome(pip);return}results.innerHTML=found.length?"":'<p class="pip-empty">No matches found</p>';found.forEach(item=>{const button=pip.document.createElement("button");button.type="button";button.className="pip-result";button.innerHTML=`<span>${item.name[0]}</span><strong>${item.name}</strong><small>${item.profile}</small>`;button.addEventListener("click",async()=>{await launch(item,false);renderPipHome(pip)});results.appendChild(button)})});input.focus()}
 async function openFloating(){const api=(window as unknown as {documentPictureInPicture?:PipApi}).documentPictureInPicture;if(!api){openDialog();return}try{if(pipRef.current&&!pipRef.current.closed){pipRef.current.focus();return}const pip=await api.requestWindow({width:300,height:300});pipRef.current=pip;pip.document.title="Chrome Helper";pip.document.body.innerHTML='<main id="root"></main>';const style=pip.document.createElement("style");style.textContent=`*{box-sizing:border-box}body{margin:0;background:#f3f0e7;color:#172018;font-family:Arial,sans-serif}#root{min-height:100vh;padding:16px;display:grid;place-items:center}.pip-plus{width:210px;height:210px;border:0;border-radius:50%;background:#d8ff43;color:#172018;font-size:110px;font-weight:200;line-height:1;cursor:pointer;box-shadow:0 18px 50px rgba(72,88,16,.22)}.pip-search{width:100%;display:grid;gap:9px}.pip-search label{font:30px Georgia,serif}.pip-search input{width:100%;padding:13px;border:1.5px solid #172018;border-radius:10px;font-size:15px}.pip-search>button[type=submit]{border:0;border-radius:9px;padding:12px;background:#172018;color:white;font-weight:700}.pip-results{display:grid;gap:7px;max-height:145px;overflow:auto}.pip-result{display:grid;grid-template-columns:34px 1fr;grid-template-rows:1fr 1fr;text-align:left;border:1px solid rgba(23,32,24,.14);border-radius:10px;background:white;padding:8px;cursor:pointer}.pip-result span{grid-row:1/3;width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#d9caff;font:italic 17px Georgia,serif}.pip-result strong{font-size:12px}.pip-result small{font-size:9px;color:#747a72}.pip-back{border:0;background:transparent;color:#60665e;font-size:11px}.pip-empty{text-align:center;color:#747a72;font-size:12px}`;pip.document.head.appendChild(style);pip.addEventListener("pagehide",()=>{pipRef.current=null});renderPipHome(pip);setStatus("Floating launcher is on top")}catch{openDialog()}}
 function handleMainButton(){if(window.matchMedia("(display-mode: standalone)").matches)openFloating();else openDialog()}
 return <main><header className="topbar"><a className="brand" href="#top"><img className="brandMark" src="/pk-logo.svg" alt="PK"/>Chrome Helper</a><div className="connection"><span className="pulse"/>{status}</div></header>
 <section className="hero" id="top"><div className="eyebrow">Chrome profile launcher</div><h1>Choose a profile.<br/><em>Get straight to admin.</em></h1><button className="launchButton" onClick={handleMainButton} aria-label="Open floating Chrome profile launcher"><span className="plus">+</span><span>Open profile</span><kbd>⌘ K</kbd></button><p className="lede">Type a name. Pick a match. Land directly in Microsoft 365 Admin.</p></section>
 <div className="destination"><span>Always opens</span><strong>admin.microsoft.com</strong><span className="north">↗</span></div>
 <dialog ref={dialogRef} onClick={e=>{if(e.target===dialogRef.current)dialogRef.current.close()}}><form onSubmit={find}><button type="button" className="close" onClick={()=>dialogRef.current?.close()} aria-label="Close">×</button><label htmlFor="profile-name">Which profile?</label><p>Type a name — close matches work too.</p><div className="inputRow"><span className="searchIcon">⌕</span><input ref={inputRef} id="profile-name" value={query} onChange={e=>{setQuery(e.target.value);setSubmitted(false)}} placeholder="e.g. naaja" autoComplete="off"/><button type="submit" disabled={!query.trim()}>Find <span>↗</span></button></div>{submitted&&<div className="results" aria-live="polite">{matches.length>1&&<h2>{matches.length} matching profiles</h2>}{matches.length===0&&<div className="empty">No matching profiles found.</div>}{matches.map((item,index)=><button type="button" className="resultButton" key={item.profile} onClick={()=>launch(item)}><span className={`avatar tone${index%3+1}`}>{item.name[0]}</span><span><strong>{item.name}</strong><small>{item.profile}</small></span><span className="arrow">Open ↗</span></button>)}</div>}</form></dialog>
 <footer>Built for Chrome on desktop <span>·</span> Your profiles stay on this device</footer></main>}
